-- MySQL Script generated by MySQL Workbench
-- Sat Jul 11 19:50:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diariodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diariodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diariodb` DEFAULT CHARACTER SET utf8 ;
USE `diariodb` ;

-- -----------------------------------------------------
-- Table `diariodb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diariodb`.`users` (
  `gmail` VARCHAR(30) NOT NULL,
  `pass` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`gmail`))
ENGINE = InnoDB;

insert into users values('alumno ','123456');
insert into users values('jhusdan ','123');
-- -----------------------------------------------------
-- Table `diariodb`.`diario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diariodb`.`diario` (
  `titulo` VARCHAR(100) NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`titulo`))
ENGINE = InnoDB;

insert into diario values('El mundo oculto','2020-07-11',' El mundo oculto es un mundo donde que pocas personas llegaron y nadie regreso para contar exepto yo');
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
